#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.61432635, 0.16747201],
       [0.94110723, 0.23728022],
       [0.00946157, 0.63049319]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-0.31265872,  0.42990318])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[107.99419676  55.6643423 ]
 [139.01401587  76.90208024]
 [179.79087372  83.36412318]
 [103.16631788  51.04334627]
 [133.08446348  78.89889684]
 [107.99419676  55.6643423 ]
 [139.01401587  76.90208024]
 [179.79087372  83.36412318]
 [103.16631788  51.04334627]
 [133.08446348  78.89889684]
 [107.99419676  55.6643423 ]
 [139.01401587  76.90208024]
 [179.79087372  83.36412318]
 [103.16631788  51.04334627]
 [133.08446348  78.89889684]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(2231.285409876558, shape=(), dtype=float64)


In [9]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 19.662090513273593
 
 Epoch count: 1 
 Loss value: 19.10996159001069
 
 Epoch count: 2 
 Loss value: 18.592185915169313
 
 Epoch count: 3 
 Loss value: 18.105169268815768
 
 Epoch count: 4 
 Loss value: 17.645746963861217
 
 Epoch count: 5 
 Loss value: 17.211131306947088
 
 Epoch count: 6 
 Loss value: 16.798865524275147
 
 Epoch count: 7 
 Loss value: 16.406783350365565
 
 Epoch count: 8 
 Loss value: 16.03297357949971
 
 Epoch count: 9 
 Loss value: 15.67574896762268
 
 Epoch count: 10 
 Loss value: 15.333618948905983
 
 Epoch count: 11 
 Loss value: 15.005265697726523
 
 Epoch count: 12 
 Loss value: 14.689523124893345
 
 Epoch count: 13 
 Loss value: 14.385358447717948
 
 Epoch count: 14 
 Loss value: 14.09185601793067
 
 Epoch count: 15 
 Loss value: 13.808203130337393
 
 Epoch count: 16 
 Loss value: 13.533677569177929
 
 Epoch count: 17 
 Loss value: 13.267636679009673
 
 Epoch count: 18 
 Loss value: 13.009507773118814
 
 Epoch count: 19 
 Loss 